### ISSUE TITLE
Parse failure when CSV has trailing newline

### ISSUE THREAD

**Issue by pib** [PostgREST/postgrest#691] opened 2016-08-08 18:46 UTC
Returns `{"details":"parse error (not enough input) at \"\"","message":"Cannot parse request payload"}`

Lots of tools that generate CSV files add a trailing newline, so this behavior tends to be frustrating.

I can work around it by using `head -c -1`, but it'd be nice if I could just curl a CSV file without having to worry about it.

**Comment by begriffs** [comment] 2016-08-08 21:14
Yeah that is annoying. I'll make a test case, check if there's an option in our CSV parsing library to make it more forgiving, and look into a fix for that library if there isn't.

**Comment by begriffs** [comment] 2017-01-25 07:35
@pib sorry for the delay on this, the upstream package cassava seems like it might be unmaintained or something. They aren't responding to my issue. I bumped it one more time. If we get no answer then it might be time to look for a replacement library.

**Comment by pib** [comment] 2017-01-25 16:45
@begriffs Thanks for the update! I've managed to work around this issue any time I've run into it, but it does seem to come up at least once every time someone new writes some code that pushes data into one of our PostgREST services :D

**Comment by begriffs** [comment] 2017-06-06 18:39
Note to self: we need to switch from cassava to something maintained like https://hackage.haskell.org/package/csv-conduit

**Comment by wolfgangwalther** [comment] 2020-12-10 09:59
This seems to be resolved by now. Couldn't reproduce, csv insert with trailing new line worked just fine.

**Closed by wolfgangwalther** 2020-12-10 09:59 UTC
Labels: csv, enhancement
