### ISSUE TITLE
PostgREST memory usage keep growing over time

### ISSUE THREAD

**Issue by yyqgituser** [PostgREST/postgrest#2251] opened 2022-04-19 06:39 UTC
### Environment

* PostgREST version: PostgREST 6.0.2

### Description of issue
I started the PostgREST with following command:

#/usr/bin/postgrest /usr/local/etc/pgrest.conf +RTS -c -M400m

The '-M' option is supposed to limit the total heap size to 400 MB.
In the database, I have very large table, and I repeatedly query the different part of the table(2000 rows per query), and monitering PostgREST process memory usage by 'top', however, the memory usage is steadily growing over time, as to now, its RES memory have exceeded 700M

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  1282 root      20   0  1.016t 762572  28276 S 0.333 0.058   3:26.07 postgrest

**Comment by wolfgangwalther** [comment] 2022-04-19 07:01
Version 6.0.2 was released more than 2,5 years ago. Did you try and reproduce with any more recent version?

**Comment by steve-chavez** [comment] 2022-04-19 16:05
@yyqgituser There were many optimizations done since 6.0.2 - it's likely this problem doesn't exist anymore.

> For some compatibility reason, we still have to use that version

Can you pinpoint which incompatibility do you have with the latest version?

**Comment by yyqgituser** [comment] 2022-04-21 07:50
@steve-chavez  I am not 100 percent sure, it should be following issue.
https://github.com/PostgREST/postgrest/issues/1643
In 6.0.2, table with self reference foreign key can work in 6.0.2, but from 7.0.1 PostgREST return status code 300 instead

**Comment by wolfgangwalther** [comment] 2022-04-21 10:55
Do you think you could set up a latest PostgREST instance on the same database for testing and run those same requests to see whether the memory leak still exists?

This would help us to decide whether we're still looking at a potential memory leak to fix or whether we're just looking at how to support your migration away from 6.0.2 here.

**Comment by yyqgituser** [comment] 2022-04-21 14:16
I have finished the test with the latest 9.0.0 version, good new is there is no memory leak.
But I still can't avoid the compatibility issue.
In short, this is my problem, I have a job table like this:
```
CREATE TABLE public.job
(
    id integer NOT NULL,
    parent_id integer,
    CONSTRAINT job_pkey PRIMARY KEY (id),
    CONSTRAINT parent_fk FOREIGN KEY (parent_id)
        REFERENCES public.job (id) MATCH SIMPLE        
)
```
Then I want to use the embeding feature of PostgREST to get the job's parent and childs in one query, like this:
```
http://127.0.0.1:3000/job?select=id,parent:job!parent_fk(id),childs:job!parent_fk (id)
```
apprently it can't work because I use the a same hint for both parent and childs. but in version 6.0.1, following ugly tick can work:
```
http://127.0.0.1:3000/job?select=id,parent:parent_id(id),childs:job.parent_id(id)
```

**Comment by steve-chavez** [comment] 2022-04-21 21:28
> http://127.0.0.1:3000/job?select=id,parent:job!parent_fk(id),childs:job!parent_fk (id)
> apprently it can't work because I use the a same hint for both parent and childs. 

@yyqgituser Can you share the error on https://github.com/PostgREST/postgrest/issues/1643?

> but in version 6.0.1, following ugly tick can work:
> http://127.0.0.1:3000/job?select=id,parent:parent_id(id),childs:job.parent_id(id)

Also the error you get for this one in the latest version.

I'm working on reducing the embedding possibilities now so maybe I can get those solved too.

**Comment by yyqgituser** [comment] 2022-04-23 15:12
@steve-chavez To make it more clear, I re-run the test, first I prepare the tables and views
`
CREATE TABLE public.job
(
    id integer NOT NULL,
    parent_id integer,
    CONSTRAINT job_pkey PRIMARY KEY (id),
    CONSTRAINT parent_fk FOREIGN KEY (parent_id)
        REFERENCES public.job (id) MATCH SIMPLE        
)

INSERT INTO public.job (id, parent_id) VALUES (1, null);
INSERT INTO public.job (id, parent_id) VALUES (2, 1);
CREATE VIEW public.job_view AS
    SELECT *
    FROM public.job;

`
Then I start a PostgREST 6.0.2 server and point to this DB server, and send ths query request:
`
http://127.0.0.1:3000/job?select=id,parent:parent_id(id),childs:job.parent_id(id)
`
Response(which is what I want):
```
[
    {
        "id": 1,
        "parent": null,
        "childs": [
            {
                "id": 2
            }
        ]
    },
    {
        "id": 2,
        "parent": {
            "id": 1
        },
        "childs": []
    }
]
```
Then I kill the 6.0.2  PostgREST server and start a PostgREST 9.0.0 server pointed to the same DB server, and send the same request above, I got this error:
```
{
    "hint": "Try changing 'parent_id' to one of the following: 'job!parent_fk', 'job_view!parent_fk'. Find the desired relationship in the 'details' key.",
    "details": [
        {
            "relationship": "parent_fk[parent_id][id]",
            "embedding": "job with job",
            "cardinality": "many-to-one"
        },
        {
            "relationship": "parent_fk[parent_id][id]",
            "embedding": "job with job_view",
            "cardinality": "many-to-one"
        }
    ],
    "message": "Could not embed because more than one relationship was found for 'job' and 'parent_id'"
}
```
Then I change the request according to the hint:
`
http://10.207.201.212:3000/job?select=id,parent:job!parent_fk(id),childs:job!parent_fk(id)
`
got a response, but it is not what I want:
```
[
    {
        "id": 1,
        "parent": [
            {
                "id": 2
            }
        ],
        "childs": [
            {
                "id": 2
            }
        ]
    },
    {
        "id": 2,
        "parent": [],
        "childs": []
    }
]
```

**Comment by steve-chavez** [comment] 2022-04-23 22:24
@yyqgituser I see what you mean and I can reproduce.

Since for self-references we rely on the `column` being the target for the embedding it's impossible to get the relationship you want as long as VIEWs are also detected - my proposal on https://github.com/PostgREST/postgrest/issues/2238#issuecomment-1092383613 would solve this.

Let's continue the discussion on https://github.com/PostgREST/postgrest/issues/2238. I'll close this one since the memory leak problem is gone on the latest version.

**Closed by steve-chavez** 2022-04-23 22:24 UTC
