### ISSUE TITLE
io tests fail on pg 9.5

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#1820] opened 2021-04-17 12:08 UTC
I just noticed that our io tests currently fail on pg 9.5.

`postgrest-with-postgresql-9.5 postgrest-test-io` returns:

```
test/io-tests/test_io.py::test_read_db_setting FAILED
test/io-tests/test_io.py::test_db_schema_notify_reload FAILED
test/io-tests/test_io.py::test_max_rows_reload FAILED
test/io-tests/test_io.py::test_max_rows_notify_reload FAILED
test/io-tests/test_io.py::test_invalid_role_claim_key_notify_reload FAILED
```

We are not running the io tests against all PG versions in CI right now - that's something we should maybe do.

PG 9.5 had its final relese February 11, 2021, and is not supported upstream anymore - but we still do. My idea was to remove 9.5 support after our next release.

In that case, we'd need to fix those tests now, to make sure everything still works with 9.5. However, I don't know whether it's worth it - should we just drop PG 9.5 right away? @steve-chavez WDYT?

**Comment by steve-chavez** [comment] 2021-04-17 15:14
This happens because `current_setting(name, bool)` is not available on [pg 9.5](https://www.postgresql.org/docs/9.5/functions-admin.html). Only `current_setting(name)` is available there.

Those python errors are `PostgrestTimedOut` because they keep trying to request the root endpoint until it responds with 200 but it never does(keeps 404ing). pre-request also has the same issue.

https://github.com/PostgREST/postgrest/blob/915d568257b00f66efe6815b00fc8bc93ec9ce3e/test/fixtures/roles.sql#L18-L20

https://github.com/PostgREST/postgrest/blob/915d568257b00f66efe6815b00fc8bc93ec9ce3e/test/fixtures/schema.sql#L1633-L1655

https://github.com/PostgREST/postgrest/blob/915d568257b00f66efe6815b00fc8bc93ec9ce3e/test/fixtures/schema.sql#L1826-L1831

**Comment by steve-chavez** [comment] 2021-04-17 15:16
I think we could fix this by just using the `current_setting(name)` variant. Not sure if it's worth it though, if we're going to drop 9.5 anyway.

**Comment by wolfgangwalther** [comment] 2021-04-17 15:17
So this is just a problem with our test-cases, but if a user on 9.5 would use `current_setting` correctly, they'd have no problem?

Then I suggest we just leave as-is, drop 9.5 after the next release - and then add the io tests with all pg versions into CI.

**Comment by steve-chavez** [comment] 2021-04-17 15:18
> So this is just a problem with our test-cases, but if a user on 9.5 would use current_setting correctly, they'd have no problem?

Yeah, I confirmed this by removing the bool from `current_setting`, tests become green.

**Comment by steve-chavez** [comment] 2021-11-26 23:21
Closed by https://github.com/PostgREST/postgrest/pull/2038/

**Comment by wolfgangwalther** [comment] 2021-11-27 10:03
I'd still like to enable io-tests for all pg versions as commented above.

**Closed** 2021-11-27 18:15 UTC
Labels: bug
