### ISSUE TITLE
multi app connect postgrest to operater postgres,  after a few days, the postgrest is blocked,  no connection to the postgres is there

### ISSUE THREAD

**Issue by miaojianxin** [PostgREST/postgrest#1765] opened 2021-03-02 02:10 UTC
application：
java app  ，by restful connect postgrest， and then opeatter the postgresql db.
the postgrest: db-pool:80
after a few days of work, the postgrest is blocked, and not work, there is no connection to the  postgresql db.
when this happend, I have to restart the postgrest, then it's ok.     after two or three days, if happend agagin.
I tried  several versions of  postgrest,  the problem is all here .
thank you .

**Comment by wolfgangwalther** [comment] 2021-03-02 09:16
Please:
- Tell us which PostgREST version you are using
- Show us the PostgREST log - does it report any connection loss or something?
- Show us the response PostgREST is giving via http once it's blocked
- Have a look at the system resources - any indication of huge memory consumption or something?

**Comment by miaojianxin** [comment] 2021-03-02 09:44
vesion：
I use 5.0 and 7.0 all have the problem.
The 5.0 version: I use my build version, in code , I adjust pool time out to 300seconds, the varible default is 10 seconds;
The 7.0 version: I use the version from install web, the db_pool_timeot i set to 600seconds

when the rest is blocked,  the cpu   fall down quickly, 
the log is stoped here , not write any thing ,  just stop here, like this
10.20.8.1 - - [02/Mar/2021:17:43:03 +0800] "POST /rpc/yt_kafka_filter HTTP/1.1" 200 - "" ""
10.20.8.1 - - [02/Mar/2021:17:43:03 +0800] "POST /rpc/yt_kafka_filter HTTP/1.1" 200 - "" ""
10.20.8.1 - - [02/Mar/2021:17:43:03 +0800] "POST /rpc/yt_kafka_filter HTTP/1.1" 200 - "" ""
10.20.8.1 - - [02/Mar/2021:17:43:03 +0800] "POST /rpc/yt_kafka_filter HTTP/1.1" 200 - "" ""
10.20.8.1 - - [02/Mar/2021:17:43:03 +0800] "POST /rpc/yt_kafka_filter HTTP/1.1" 200 - "" ""
10.20.8.1 - - [02/Mar/2021:17:43:03 +0800] "POST /rpc/yt_kafka_filter HTTP/1.1" 200 - "" ""

**Comment by wolfgangwalther** [comment] 2021-03-02 09:53
So what is "PostgREST is blocked" then?

Does PostgREST still respond to a http request with any response in this state? Or does it time out?

Can you confirm that this still happens with the latest nightly? https://github.com/PostgREST/postgrest/releases/tag/nightly

**Comment by wolfgangwalther** [comment] 2021-03-16 07:18
This looks like it could be a duplicate of #1399. There is a suggestion in the other issue how to solve it, too.

**Closed by wolfgangwalther** 2021-03-16 07:18 UTC
Labels: needs-issuer-feedback
