### ISSUE TITLE
type cast with horizontal filtering

### ISSUE THREAD

**Issue by fjf2002** [PostgREST/postgrest#1952] opened 2021-09-17 16:26 UTC
### Environment
* PostgreSQL version: docker image, postgresql 13.4
* PostgREST version: docker image, postgrest 8
* Operating system: WSL2

### Description of issue
On page https://postgrest.org/en/v8.0/api.html?highlight=filtering#vertical-filtering-columns I learnt that type casting the columns is possible.

I would like to type cast on horizontal filtering, i. e. I need something at the REST level that translates at the SQL level to:
```sql
SELECT *
FROM foo
WHERE foo.bar = 'myvalue'::mycustomtype
```

Let's put it like this: Probably horizontal filtering on any user defined type needs a string-to-user-defined-type-cast like this? Are user defined types currently locked out from horizontal filtering?

More precisely, foo.bar has type regclass, and I am failing with both 
```
foo.bar=eq.my_table

foo.bar=eq.'my_table'::regclass
```
(at REST level)

**Comment by steve-chavez** [comment] 2021-09-19 04:38
@fjf2002 You can do this with a computed column, check this previous answer here: https://github.com/PostgREST/postgrest/issues/1651#issuecomment-729099728

> Let's put it like this: Probably horizontal filtering on any user defined type needs a string-to-user-defined-type-cast like this? Are user defined types currently locked out from horizontal filtering?

Hm, this feature request has come up before but the main drawback of implementing casting at the filter level is that it invalidates indexes. [computed columns](https://postgrest.org/en/v8.0/api.html#computed-columns) are safer in that regard.

**Comment by fjf2002** [comment] 2021-09-20 06:49
@steve-chavez Thank You for the hint with computed columns. That works.

>  the main drawback of implementing casting at the filter level is that it invalidates indexes

Are you sure that a WHERE clause like
```sql
WHERE mycolumn = myconstant::mytype
```
does NOT USE the index on mycolumn? I would double that, because the type cast happens on the constant value, not on the column.

A test of both sql statements
```sql
explain select * from foo where bar = 25603;

explain select * from foo where bar = 'person'::regclass;
```

... showed me both times the same query plan, using the index on table_oid.

**Comment by wolfgangwalther** [comment] 2021-09-20 11:06
> Are you sure that a WHERE clause like
> 
> ```sql
> WHERE mycolumn = myconstant::mytype
> ```
> 
> does NOT USE the index on mycolumn? I would double that, because the type cast happens on the constant value, not on the column.

Please see this https://github.com/PostgREST/postgrest/issues/1651#issuecomment-729560457 for the background on this.

The problem is not expected when the right cast is used, but when the wrong cast is used. This could increase the surface for DDoS attacks.

**Comment by wolfgangwalther** [comment] 2021-09-20 11:07
As of right now, the same reasoning as in https://github.com/PostgREST/postgrest/issues/1651#issuecomment-735244691 holds true. Unless we find better arguments to support a syntax like this, we're unlikely to continue with this, so I'll close this for now.

**Closed by wolfgangwalther** 2021-09-20 11:07 UTC

**Comment by fjf2002** [comment] 2021-09-20 17:05
ok, thanks!
