### ISSUE TITLE
Help with embedded ambiguity, upgrading from v6.0.2 to v9.0.0

### ISSUE THREAD

**Issue by bolerodan** [PostgREST/postgrest#2070] opened 2021-12-03 15:35 UTC
So we are currently still on version 6.0.2 of PostgREST and a while back there was lots of talk about resource ambiguity, duct typing, specifying foreign key constraints, etc.

This has held us from upgrading due to these changes, but version 9.0 has introduced some great features we actually want, so we are upgrading, but that requires quite the trickle down effect since duct typing seems to be removed. In fact it's amazing we managed to get so far with the duct typing, but I digress.

Issues I'm having. For starters here is an example table structure 

```
                                                Table "api.plate"
      Column      |           Type           | Collation | Nullable |                   Default                   
------------------+--------------------------+-----------+----------+---------------------------------------------
 plate_id         | integer                  |           | not null | nextval('api.plate_plate_id_seq'::regclass)

Indexes:
    "plate_pkey" PRIMARY KEY, btree (plate_id)


                                           Table "api.well"
     Column     |       Type       | Collation | Nullable |                  Default                  
----------------+------------------+-----------+----------+-------------------------------------------
 well_id        | integer          |           | not null | nextval('api.well_well_id_seq'::regclass)
 plate_id       | integer          |           |          | 
 extract_id     | integer          |           |          | 
 parent_well_id | integer          |           |          | 

Indexes:
    "well_pkey" PRIMARY KEY, btree (well_id)
Foreign-key constraints:
    "well_extract_id_fkey" FOREIGN KEY (extract_id) REFERENCES api."extract"(extract_id) ON DELETE SET NULL
    "well_parent_well_id_fkey" FOREIGN KEY (parent_well_id) REFERENCES api.well(well_id) ON DELETE SET NULL
    "well_plate_id_fkey" FOREIGN KEY (plate_id) REFERENCES api.plate(plate_id) ON DELETE CASCADE


                                              Table "api.plate_plan_step"
       Column       |  Type   | Collation | Nullable |                             Default                             
--------------------+---------+-----------+----------+-----------------------------------------------------------------
 plate_plan_step_id | integer |           | not null | nextval('api.plate_plan_step_plate_plan_step_id_seq'::regclass)
 plate_plan_id      | integer |           |          | 
 from_well_id       | integer |           |          | 
 to_well_id         | integer |           |          | 
 to_plate_id        | integer |           |          | 
Indexes:
    "plate_plan_step_pkey" PRIMARY KEY, btree (plate_plan_step_id)
Foreign-key constraints:
    "plate_plan_step_from_well_id_fkey" FOREIGN KEY (from_well_id) REFERENCES api.well(well_id) ON DELETE CASCADE
    "plate_plan_step_plate_plan_id_fkey" FOREIGN KEY (plate_plan_id) REFERENCES api.plate_plan(plate_plan_id) ON DELETE CASCADE
    "plate_plan_step_to_plate_id_fkey" FOREIGN KEY (to_plate_id) REFERENCES api.plate(plate_id) ON DELETE CASCADE
    "plate_plan_step_to_well_id_fkey" FOREIGN KEY (to_well_id) REFERENCES api.well(well_id) ON DELETE CASCADE
```

currently in version 6.0.2, we can query for a plate, and emebed its related wells

```
/plate/10?select=*,well(*)
```

However now, we get the following amiguity

```
{
    "details": [
      {
        "cardinality": "many-to-many", 
        "embedding": "plate with well", 
        "relationship": "api.well[well_plate_id_fkey][well_parent_well_id_fkey]"
      }, 
      {
        "cardinality": "many-to-many", 
        "embedding": "plate with well", 
        "relationship": "api.plate_plan_step[plate_plan_step_to_plate_id_fkey][plate_plan_step_from_well_id_fkey]"
      }, 
      {
        "cardinality": "many-to-many", 
        "embedding": "plate with well", 
        "relationship": "api.plate_plan_step[plate_plan_step_to_plate_id_fkey][plate_plan_step_to_well_id_fkey]"
      }, 
      {
        "cardinality": "one-to-many", 
        "embedding": "plate with well", 
        "relationship": "well_plate_id_fkey[plate_id][plate_id]"
      }
    ], 
    "hint": "Try changing 'well' to one of the following: 'well!well', 'well!plate_plan_step', 'well!plate_plan_step', 'well!well_plate_id_fkey'. Find the desired relationship in the 'details' key.", 
    "message": "Could not embed because more than one relationship was found for 'plate' and 'well'"
  }
```

So few things, curious that its even bothering going down the self referencing well_parent_well_id foreign key to get to plate_id. 

The suggestion `well!well` also doesnt work, also curious why its going through `plate_plan_step`, through `to_well_id` and `from_well_id` to get to `plate_id`

Unless I'm reading these wrong.

Now I understand, that specifying the remote table `well` foreign key constraint name will work. In this case doing the following works in version 9.0.0

```
/plate/query?select=*,well!well_plate_id_fkey(*)
```

But unfortunately, we dont expose foreign key names, and some foreignkey names are _incredibly_ long due to migrations created from ORM. I do know in one of the PRs / issues the suggestion was to just rename these foreignkeys, but this is heavily overlooked and now binds postgrest to our database implementation, again I digress.

Any suggestions here, or do we have to live with exposing foreign key constraint names within our schema output system we use?

Circling back to its suggestion hint of `well!well` in my mind okay, this could work, its saying look only at the well table, ignore the other relationship paths it found, and it should find `plate_id` directly on the table but this results in

```
 {
    "code": "42712", 
    "details": null, 
    "hint": null, 
    "message": "table name \"well\" specified more than once"
  }
```

**Comment by steve-chavez** [comment] 2021-12-03 19:25
> /plate/query?select=*,well!well_plate_id_fkey(*)

Note that you can use the columns instead of the foreign keys, as mentioned in the [docs](https://postgrest.org/en/v9.0/api.html#target-disambiguation).

> and it should find plate_id directly on the table but this results in

So here you are doing: `/plate/query?select=*,well!plate_id(*)` correct?

**Comment by bolerodan** [comment] 2021-12-03 19:28
So I originally hoping that specifying the remote column name would work, in this case `plate_id` however doing this

```
/plate/query?select=*,well!plate_id(*)
```

still provides me with the following error

```
{
    "details": [
      {
        "cardinality": "many-to-many", 
        "embedding": "plate with well", 
        "relationship": "api.well[well_plate_id_fkey][well_parent_well_id_fkey]"
      }, 
      {
        "cardinality": "many-to-many", 
        "embedding": "plate with well", 
        "relationship": "api.plate_plan_step[plate_plan_step_to_plate_id_fkey][plate_plan_step_from_well_id_fkey]"
      }, 
      {
        "cardinality": "many-to-many", 
        "embedding": "plate with well", 
        "relationship": "api.plate_plan_step[plate_plan_step_to_plate_id_fkey][plate_plan_step_to_well_id_fkey]"
      }, 
      {
        "cardinality": "one-to-many", 
        "embedding": "plate with well", 
        "relationship": "well_plate_id_fkey[plate_id][plate_id]"
      }
    ], 
    "hint": "Try changing 'well' to one of the following: 'well!well', 'well!plate_plan_step', 'well!plate_plan_step', 'well!well_plate_id_fkey'. Find the desired relationship in the 'details' key.", 
    "message": "Could not embed because more than one relationship was found for 'plate' and 'well'"
  }
```

**Comment by steve-chavez** [comment] 2021-12-04 18:37
Hm, I think the many-to-many detection is causing issues here.

@bolerodan Can you share sample DDL for you tables(no data, only schema) so we can reproduce?

**Comment by bolerodan** [comment] 2021-12-05 00:52
Hey @steve-chavez  thanks a lot for looking into this. Here is a sample DDL of the shown tables from above

```
create table plate (
    plate_id int primary key GENERATED ALWAYS AS IDENTITY
);

create table extract (
    extract_id int primary key GENERATED ALWAYS AS IDENTITY
);

create table well (
    well_id int primary key GENERATED ALWAYS AS IDENTITY,
    plate_id int not null,
    extract_id int,
    parent_well_id int,
   CONSTRAINT well_extract_id_fkey
      FOREIGN KEY(extract_id) 
	  REFERENCES extract(extract_id),
   CONSTRAINT well_parent_well_id_fkey
      FOREIGN KEY(parent_well_id) 
	  REFERENCES well(well_id),
   CONSTRAINT well_plate_id_fkey
      FOREIGN KEY(plate_id) 
	  REFERENCES plate(plate_id)
);

create table plate_plan (
    plate_plan_id int primary key GENERATED ALWAYS AS IDENTITY
);

create table plate_plan_step (
    plate_plan_step_id int primary key GENERATED ALWAYS AS IDENTITY,
    plate_plan_id int not null,
    from_well_id int,
    to_well_id int,
    to_plate_id int,
   CONSTRAINT plate_plan_step_from_well_id_fkey
      FOREIGN KEY(from_well_id)
	  REFERENCES well(well_id),
   CONSTRAINT plate_plan_step_plate_plan_id_fkey
      FOREIGN KEY(plate_plan_id)
	  REFERENCES plate_plan(plate_plan_id),
   CONSTRAINT plate_plan_step_to_plate_id_fkey
      FOREIGN KEY(to_plate_id) 
	  REFERENCES plate(plate_id),
   CONSTRAINT plate_plan_step_to_well_id_fkey
      FOREIGN KEY(to_well_id)
	  REFERENCES well(well_id)
);


-- create one plate
insert into plate values (DEFAULT);
-- attach two wells to plate
insert into well (plate_id) values (1), (1);
-- create plate plan
insert into plate_plan(plate_plan_id) values (DEFAULT);
-- attach plate plan step to plate plan and to one of the created wells
insert into plate_plan_step(plate_plan_id, from_well_id) values (1,2);
```

**Comment by wolfgangwalther** [comment] 2021-12-06 08:40
> `/plate/query?select=*,well!plate_id(*)`
> still provides me with the [...] error

There's a two things going wrong here on our side:

- First, `plate_id` as a column hint is only shown for the `o2m` relationship - but is actually matched as the source table column for all relationships in the list.

    The relationship display is quite mis-leading here:
    ```json
      "relationship": "api.well[well_plate_id_fkey][well_parent_well_id_fkey]"
      "relationship": "api.plate_plan_step[plate_plan_step_to_plate_id_fkey][plate_plan_step_from_well_id_fkey]"
      "relationship": "api.plate_plan_step[plate_plan_step_to_plate_id_fkey][plate_plan_step_to_well_id_fkey]"

      "relationship": "well_plate_id_fkey[plate_id][plate_id]"
    ```

    The first three are m2m and are displayed as `schema.table[fk1][fk2]`. The last one is o2m and is displayed as `fk[col1][col2]`.

    This makes it impossible to identify the problem when using `well!plate_id`.

- I think the "valid" examples merged in #2031 are just broken:
  - `well!well` is listed, but using it throws this error:
    ```json
    {
      "hint":null,
      "details":null,
      "code":"42712",
      "message":"table name \"well\" specified more than once"
    }
    ```
  - `well!plate_plan_step` is listed twice, and - as expected - returns another ambiguous error when using it.

---

I'm not sure whether we will be able to easily fix #2031 or whether we should just revert it.

In terms of the `relationship` key, we need to somehow find a way to display everything that goes into a relationship in there, for all relationship types:
- optionally junction table name
- (both) FKs
- all column names that can be matched with a hint

**Comment by wolfgangwalther** [comment] 2021-12-06 08:46
> Any suggestions here, or do we have to live with exposing foreign key constraint names within our schema output system we use?

Basically: Yes. Using constraint names is the one solution that will not cause any unexpected errors, due to adding new tables, columns, relationships, changing their names or other things like that. That's assuming that you name your constraints uniquely. 

Unfortunately, using constraint names is not in line with our schema isolation approach, because constraint names are not set in the api schema, but directly at the table level.

I still think, that using constraint names for embedding is the "right" way to do it right now and everything else we support is just for convenience/backwards compatibility - but in the end it's often causing more problems than it solves.

**Comment by bolerodan** [comment] 2021-12-06 13:38
Thanks for looking into this @wolfgangwalther . So looks like we'll have to stick to using V6.0 right now as these changes are too breaking. Exposing foreignkey constraint hints are definitely handy for composite key situations and I get why those are exposed and recommended but unfortunately it ripples too far into other services or code bases that use our database. So it wouldnt be a simple thing to rename all constraints.

Our staff understand the concepts of columns, so even if we update and no longer have duct typing, but forces our staff to hint with remote or local column names to join, that's something that they can manage.

If the goal of the project is to not allow specifying remote fk column names but moving towards constraint name joining/embedding only, I'll have to seriously consider the implications of possibly manually managing and enforcing foreign key constraint naming and exposing those through our self documenting api/database but these issues are all more about us.

As of now we'll stick with our current version of PostgREST

**Comment by steve-chavez** [comment] 2021-12-06 17:10
> If the goal of the project is to not allow specifying remote fk column names but moving towards constraint name joining/embedding only,

Not really. Column name embedding will stay, but I think we need to have an additional way to add hints since stuffing columns of composite keys into `select` would make it unreadable. It could be like:

```http
GET /clients?select=*,projects(*)&projects.keyjoin=col1,col2,col3
```

(Borrowing the `keyjoin` term from: https://www.sqlines.com/sybase-asa/key_join)

**Comment by bolerodan** [comment] 2021-12-06 17:17
Cool, that definitely looks much better than jamming everything into the select. Our database is highly interconnected so if there is any way I can help with providing more DDL samples from our side (obfuscated in naming in several cases but that shouldnt matter) I'll gladly help that way.

Thanks for going through this with me.

**Comment by laurenceisla** [comment] 2021-12-07 03:11
> So few things, curious that its even bothering going down the self referencing well_parent_well_id foreign key to get to plate_id.

It seems that embedding with a self referencing table is giving all these ambiguous possibilities. Because `well` can self reference, PostgREST detects a `one-to-many` and `many-to-many` relationship between `well` and itself. Now, when `plate` embeds `well`, PostgREST won't know if it should do it directly or use the intermediate relationship i.e. through `well` itself due to the self reference.

> also curious why its going through plate_plan_step, through to_well_id and from_well_id to get to plate_id

In this case, `plate` can reference `plate_pĺan_step` which itself can also reference `well`, PostgREST detects this as a possible `many-to-many` relationship between `pĺate` and `well` thus giving the ambiguity error.

> > `/plate/query?select=*,well!plate_id(*)`
> > still provides me with the [...] error
> 
> There's a two things going wrong here on our side:
> 
>     * First, `plate_id` as a column hint is only shown for the `o2m` relationship - but is actually matched as the source table column for all relationships in the list.
>       The relationship display is quite mis-leading here:
>       ...
>       The first three are m2m and are displayed as `schema.table[fk1][fk2]`. The last one is o2m and is displayed as `fk[col1][col2]`.
>       This makes it impossible to identify the problem when using `well!plate_id`.

Maybe doing something like `table[fk1[col1][col2]][fk2[col3][col4]]` would make it more explicit to the client side (kinda ugly, though) or perhaps adding a new key would help.

>     * I think the "valid" examples merged in [Include valid examples in the hint for ambiguous embedding #2031](https://github.com/PostgREST/postgrest/pull/2031) are just broken:
>       
>       * `well!well` is listed, but using it throws this error:

Yes, this was an oversight on my part for this use case, using the foreign key constraint as you mentioned should fix this.

>       * `well!plate_plan_step` is listed twice, and - as expected - returns another ambiguous error when using it.
> 

I think this is related to the impossible to disambiguate embedding case specified in the [spec tests](https://github.com/PostgREST/postgrest/blob/595c2a5257f2b12bce15f8b032999e4c337fe030/test/Feature/EmbedDisambiguationSpec.hs#L93-L128). Maybe a conditional hint is needed for these instances.

> I'm not sure whether we will be able to easily fix #2031 or whether we should just revert it.

This should be fixed by replacing the hint with the foreign key constraint as you mentioned, although more analysis needs to be made (for instance the first `m2m` and last `o2m` disambiguation will have the same hint). Maybe also the "can't disambiguate" hint would be easier to do after that. I'll check if there are other use cases related to this one too.

> In terms of the `relationship` key, we need to somehow find a way to display everything that goes into a relationship in there, for all relationship types:
> 
>     * optionally junction table name
> 
>     * (both) FKs
> 
>     * all column names that can be matched with a hint

You mean doing something like `table[fk1[col1][col2]][fk2[col3][col4]]` or maybe adding another key?

**Comment by laurenceisla** [comment] 2021-12-16 02:14
OK, here's more insight into this issue:

1. The only way to disambiguate a `many-to-many` relationship is to use `target!hint` where `target` is the target table or view and `hint` is the intermediate table or view. It won't work if the `hint` is a foreign key from the intermediate table. (Correct me if I'm wrong)

So, in this case, doing `well!well_plate_id_fkey` works only for the `one-to-many` disambiguation, not the first `many-to-many`.

2. Point 1 leads me to believe that doing `plate?select=well!well(*)` *should* work. I interpret it as this relationship: one `plate` has many (intermediate) `well`s and many (intermediate) `well`s belong to one `well`. This is also how PostgREST sees it in the schema cache:

```
{
	"cardinality": "many-to-many", 
	"embedding": "plate with well", 
	"relationship": "api.well[well_plate_id_fkey][well_parent_well_id_fkey]"
}
```

Now, using `well!well` generates the following SQL statement:

```sql
WITH pgrst_source AS (
  SELECT "api"."plate".*, COALESCE ((
      SELECT json_agg("plate".*)
      FROM (
         SELECT "api"."well".*
         FROM "api"."well", "api"."well"
         WHERE "api"."plate"."plate_id" = "api"."well"."plate_id" 
         	AND "api"."well"."well_id" = "api"."well"."parent_well_id"
      ) "plate"
  ), '[]') AS "well"
  FROM "api"."plate"
)
SELECT
  null::bigint AS total_result_set,
  pg_catalog.count(_postgrest_t) AS page_total,
  array[]::text[] AS header,
  coalesce(json_agg(_postgrest_t), '[]')::character varying AS body,
  nullif(current_setting('response.headers', true), '') AS response_headers,
  nullif(current_setting('response.status', true), '') AS response_status
FROM (SELECT * FROM pgrst_source) _postgrest_t;
```

Returning this error:

```json
{
  "hint":null,
  "details":null,
  "code":"42712",
  "message":"table name \"well\" specified more than once"
}
```

If there were aliases for the `target` and the intermediate `hint`, the statement wouldn't fail:

```sql
-- ...
          SELECT target.*
		  FROM "api"."well" as target, "api"."well" as hint
		  WHERE "api"."plate"."plate_id" = hint."plate_id" 
			AND target."well_id" = hint."parent_well_id"  
-- ...
```

I think maybe this use case should be implemented although it does not seem very common, e.g. in this issue the relationship wanted is `plates` and its `well`s (not between `plates` and the parent `well`s).

**Comment by wolfgangwalther** [comment] 2021-12-16 18:31
> If there were aliases for the `target` and the intermediate `hint`, the statement wouldn't fail:

I think "hint" is not appropriate as an alias. `junction` and `target` would be more appropriate (many more possible names [here](https://en.wikipedia.org/wiki/Associative_entity)), since the case you are describing is really a case of an m2m relationship where the target and the junction table are the same, because of a self-reference on the junction table. This is indeed quite a special case.

> The only way to disambiguate a many-to-many relationship is to use target!hint where target is the target table or view and hint is the intermediate table or view. It won't work if the hint is a foreign key from the intermediate table. (Correct me if I'm wrong)

I don't think so. Hinting with constraint names should be possible in the general case. However, if you tested this with the wells example here, then you'd run into a [similar issue as described previously](https://github.com/PostgREST/postgrest/issues/1643#issuecomment-721417728) regarding self-reference: If you hint with the constraint name, we can't tell which direction we should use the constraint in - both ways are possible, since it's a self-reference. I can't find the issue/comment now, but I think we had that "table name specified more than once" already. The problem here is, that the first item in the disambiguation response really should be two items, both ways to traverse the self-reference are collapsed into one `"api.well[well_plate_id_fkey][well_parent_well_id_fkey]"`.

In the above mentioned issue we had [multiple ideas](https://github.com/PostgREST/postgrest/issues/1643#issuecomment-722324909) how to solve that:
- Use table or column names to disambiguate between the m2o and o2m embeddings. This is not possible here, because the self-reference is part of an m2m relationship, so the target needs to be the table in any case.
- Use cardinality as a hint, e.g. `!m2o` or `!o2m`. Not possible for the same reason, because we actually want to have a m2m relationship.

This might be one of the cases where we actually need [multiple hints](https://github.com/PostgREST/postgrest/issues/1907) to be able to embed successfully. There was [another suggestion about making the order of hints relevant](https://github.com/PostgREST/postgrest/issues/1907#issuecomment-899019330 )as well. If that was the case, then we could disambiguate this request successfully with:
- `plate?select=wells!well_plate_id_fkey!parent_well_id!well_id`
- `plate?select=wells!well_plate_id_fkey!well_id!parent_well_id`

The difference being in the order of which those hints would be given - they basically describe a path to take between origin and target.

This leads me to another idea: Given the request for `plate?select=wells!well_parent_well_id_fkey`, it's clear that an m2m relationship is requested. But since the constraint name is the self-reference, it's not clear in which direction this FK should be taken. How about a direction operator for constraint hints?

Maybe consider `!` as a non-directional hint (can be taken for both directions), and then replace that with `<` or `>`:
- `plate?select=wells>well_parent_well_id_fkey`
- `plate?select=wells<well_parent_well_id_fkey`

I think that would be more powerful than the `!o2m` or `!m2o` hints to disambiguate self-references.

**Comment by steve-chavez** [comment] 2021-12-16 23:31
> I think that would be more powerful than the !o2m or !m2o hints to disambiguate self-references.
> Maybe consider ! as a non-directional hint (can be taken for both directions), and then replace that with < or >:

That one sounds like a good alternative for https://github.com/PostgREST/postgrest/issues/1643

---

Taking a step back, isn't the main problem here that we are too liberal in detecting a many-to-many relationship?

We discussed the following idea before somewhere. If we were to detect a many-to-many when a [junction table](https://en.wikipedia.org/wiki/Associative_entity#:~:text=An%20associative%20(or%20junction)%20table,to%20the%20individual%20data%20tables.) strictly contains only foreign keys of two tables then nor `plate_plan_step` or `well` would appear as junction tables in the original error https://github.com/PostgREST/postgrest/issues/2070#issue-1070712275.

I think this would be good for all cases because otherwise adding a view or table is likely to break clients requests.

We could have a `db-embed-legacy-junction = true` config to have a better transition for this change. Turning that config to false in a major version release.

**Comment by wolfgangwalther** [comment] 2022-01-01 12:46
> Taking a step back, isn't the main problem here that we are too liberal in detecting a many-to-many relationship?
> 
> We discussed the following idea before somewhere. If we were to detect a many-to-many when a [junction table](https://en.wikipedia.org/wiki/Associative_entity#:~:text=An%20associative%20(or%20junction)%20table,to%20the%20individual%20data%20tables.) strictly contains only foreign keys of two tables then nor `plate_plan_step` or `well` would appear as junction tables in the original error [#2070 (comment)](https://github.com/PostgREST/postgrest/issues/2070#issue-1070712275). So a strict junction can have 2 foreign keys plus other columns that are not foreign keys.

Right, I agree. Detecting m2m relationships is just syntactic sugar anway, because you could also embed twice right now with o2m + m2o through the junction table. So the whole point of having m2m detection is just to make the querystring simpler and the output nicer - but not functional.

> We could have a `db-embed-legacy-junction = true` config to have a better transition for this change. Turning that config to false in a major version release later.

Maybe we can first just add the ability to chain multiple embeds (e.g. by giving multiple hints **with the result of joining multiple times, once per hint**). This could then easily replace current usages of non-strict-junctions with just an additional chain element/hint. Order of those elements/hints would matter, and we could implement https://github.com/PostgREST/postgrest/issues/2070#issuecomment-996073047 for directional hints, too.

Having that, I don't think we'd need to add the legacy config option. We could just announce a breaking change with a clear migration path, possibly with the help of https://github.com/PostgREST/postgrest/pull/1926#issuecomment-913659308 to point users directly to it, when they encounter an unresolvable embed.

**Comment by steve-chavez** [comment] 2022-04-09 01:08
> Right, I agree. Detecting m2m relationships is just syntactic sugar anway, because you could also embed twice right now with o2m + m2o through the junction table.

Yeah, so clients can still get the results of non-strict junctions.

---

> So a strict junction can have 2 foreign keys plus other columns that are not foreign keys.

I'd like to add an additional restriction to the [above](https://github.com/PostgREST/postgrest/issues/2070#issuecomment-996274638) idea.

Even with 2 FKs the table should not be considered a junction. The [classic example](https://en.wikipedia.org/wiki/Associative_entity#:~:text=An%20associative%20(or%20junction)%20table,to%20the%20individual%20data%20tables.) always has a PK on these FK columns, so we should apply the same.

Otherwise we'd be still too liberal for m2m's and these can break APIs just when adding tables.

**Closed** 2022-04-25 17:35 UTC
Labels: bug, embedding

**Comment by steve-chavez** [comment] 2022-04-26 20:46
@bolerodan Can you confirm https://github.com/PostgREST/postgrest/pull/2262 solves your issue? Binaries at https://github.com/PostgREST/postgrest/actions/runs/2221841083

**Comment by bolerodan** [comment] 2022-04-27 14:05
@steve-chavez 

Just looking at that build, doing some rough tests with our current schema, doing a query like the following

```
/plate?select=*,well(*,plate_plan_step!from_well_id!inner(*),parent_well:parent_well_id(*))
```

now works, before trying to embedd`well` onto `plate` like mentioned in OP failed.

This build also seems to have fixed another embedding issue not mentioned here as well.
