### ISSUE TITLE
POST a nested  json returns 500

### ISSUE THREAD

**Issue by stefanosvarsanis** [PostgREST/postgrest#1281] opened 2019-04-21 10:37 UTC
### Environment

* PostgreSQL version: latest docker image
* PostgREST version: latest docker image
* Operating system: mac os
* Sending post from POSTman standalone

### Description of issue
When posting a json where a field has a nested json returns 500 error.
For example the below json

`{
"advertise_elsewhere": false,
        "form_settings": {
            "phone": "enabled",
            "avatar": "enabled",
            "resume": "enabled",
            "address": "enabled",
            "summary": "enabled",
            "headline": "enabled",
            "education": "enabled",
            "experience": "enabled",
            "cover_letter": "enabled"
        },
        "checksum": "1e66371c206df82ffxxxxxx",
        "visible": true
}`

will result in the below error
`{
    "hint": null,
    "details": null,
    "code": "XX000",
    "message": "Syntax error near '\"' at position 14"
}`
By the way the position is not correct.
Any help with this? Do I need to quote the json in some way, i've tried a lot and nothing works. 
Thanks in advance

**Comment by Qu4tro** [comment] 2019-04-21 18:07
Couldn't reproduce the issue, with a couple of tests.

Could you provide a minimal schema and the curl command (you can export it with postman) that results in your issue?

**Comment by Qu4tro** [comment] 2019-04-21 18:08
For reference, tests used to try to reproduce:

```
From 2e53094ecf207cc472665168f5c9d10e566437e5 Mon Sep 17 00:00:00 2001
From: Xavier Francisco
Date: Sun, 21 Apr 2019 14:39:20 +0100
Subject: [PATCH] Add tests

---
 test/Feature/InsertSpec.hs | 20 +++++++++++++++++++-
 1 file changed, 19 insertions(+), 1 deletion(-)

diff --git a/test/Feature/InsertSpec.hs b/test/Feature/InsertSpec.hs
index ab491c1..357e076 100644
--- a/test/Feature/InsertSpec.hs
+++ b/test/Feature/InsertSpec.hs
@@ -201,7 +201,7 @@ spec actualPgVersion = do
       it "fails returning a 409 Conflict" $
         post "/withUnique"  [json| { "uni":"nodup", "extra":"e2" } |] `shouldRespondWith` 409
 
-    context "jsonb" $ do
+    context "json column type" $ do
       it "serializes nested object" $ do
         let inserted = [json| { "data": { "foo":"bar" } } |]
             location = "/json?data=eq.%7B%22foo%22%3A%22bar%22%7D"
@@ -224,6 +224,24 @@ spec actualPgVersion = do
           , matchHeaders = ["Location" <:> location]
           }
 
+    context "jsonb column type" $ do
+      it "serializes nested object" $ do
+        request methodPost "/jsonb_test" []
+                [json| { "id": 5, "data": { "foo":"bar" } } |]
+          `shouldRespondWith` ""
+                { matchStatus  = 201
+                , matchHeaders = ["Location" <:> "/jsonb_test?id=eq.5"]
+                }
+
+      it "serializes nested object when asking with return=representation" $ do
+        request methodPost "/jsonb_test"
+                [("Prefer", "return=representation")]
+                [json| { "id": 6, "data": { "foo":"bar" } } |]
+          `shouldRespondWith` [json|[{ "id": 6, "data": { "foo":"bar" } }]|]
+                { matchStatus  = 201
+                , matchHeaders = ["Location" <:> "/jsonb_test?id=eq.6"]
+                }
+
     context "empty objects" $ do
       it "successfully inserts a row with all-default columns" $ do
         post "/items" "{}" `shouldRespondWith` ""
-- 
2.21.0

```

**Comment by steve-chavez** [comment] 2019-04-25 17:44
I also can't reproduce.

POSTing nested json works normally for me, without quoting.

We would need a sample schema to work on this.

The `"code": "XX000", "message": "Syntax error near '\"' at position 14"` is weird though, usually pg gives a more informative error that includes the type. Seems more like invalid SQL generation.

**Comment by stefanosvarsanis** [comment] 2019-05-06 15:30
Thanks for looking into this. 
First I start the docker using this command: 
`docker run --name post --rm -p 3000:3000 -e PGRST_DB_URI='postgres://master:ZZZZZZZZZZZ:5432/postgres' -e PGRST_DB_SCHEMA='public' -e PGRST_DB_ANON_ROLE='master' postgrest/postgrest`

Then I do a get request to get the jobs (http://localhost:3000/jobs) where it is an array full of these objects:
```
{
        "id": 1,
        "account_id": 424243,
        "title": "Custom Hire stage",
        "code": "",
        "description": "<p>g like bold headings and lists to make text easier to read</p><p>Avoid discriminatory language:</p><ul> <li>Yes: students, native-level, they</li> <li>No: college studg like bold headings and lists to make text easier to readAvoid discriminatory language:<ul> <li>Yes: students, native-level, they</li> <li>No: college studg like bold headings and lists to make text easier to readAvoid discriminatory language:<ul> <li>Yes: students, native-level, they</li> <li>No: college studg like bold headings and lists to make text easier to readAvoid discriminatory language:<ul> <li>Yes: students, native-level, they</li> <li>No: college stud easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> easier to readAvoid discriminatory language:<ul></ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul>",
        "state": "draft",
        "created_at": "2019-02-19T13:20:28.515833",
        "updated_at": "2019-02-19T13:21:30.458534",
        "shortcode": "1586BC269C",
        "published_on": null,
        "candidates_count": 0,
        "country_code": "GR",
        "state_code": "",
        "city": "",
        "requirement_summary": "<p>g like bold headings and lists to make text easier to read</p><p>Avoid discriminatory language:</p><ul> <li>Yes: students, native-level, they</li> <li>No: college stud</li> </ul>",
        "benefit_summary": "<p>g like bold headings and lists to make text easier to read</p><p>Avoid discriminatory language:</p><ul> <li>Yes: students, native-level, they</li> <li>No: college stud</li> </ul>",
        "telecommuting": false,
        "advertise_country_code": null,
        "advertise_state_code": null,
        "advertise_city": null,
        "zip_code": "",
        "employment_type": "",
        "industry": "",
        "experience": "",
        "salary_currency": "971",
        "advertise_elsewhere": false,
        "form_settings": {
            "phone": "enabled",
            "avatar": "enabled",
            "resume": "enabled",
            "address": "enabled",
            "summary": "enabled",
            "headline": "enabled",
            "education": "enabled",
            "experience": "enabled",
            "cover_letter": "enabled"
        },
        "checksum": "7dfdfdfdfaff4a8783bb5c727192b84c9fb0cf213d",
        "visible": false
    }
```

So the problem seems to be when inserting the form_settings. Not sure what to look for in the db schema.

**Comment by Qu4tro** [comment] 2019-05-10 23:17
Could you post the complete curl request?

**Comment by stefanosvarsanis** [comment] 2019-05-16 11:21
Actually I am doing this through Postman standalone version on Mac

**Comment by Qu4tro** [comment] 2019-05-20 09:47
Postman has a option to get the curl equivalent of the request it is doing. Label 'Code' on the right side at the same level of headers and body tabs.

**Comment by robx** [comment] 2019-05-27 15:41
Might this be the same issue as shown by the test cases in https://github.com/PostgREST/postgrest/pull/1306?

There was a change in the behavior of `record_to_json` between PostgreSQL 9.6 and PostgreSQL 10:
- version 9.6 appears to handle embedded quoted JSON fine, but not composite keys (directly included JSON)
- version 10 appears to have turned this around

**Comment by stefanosvarsanis** [comment] 2019-06-20 16:17
> Postman has a option to get the curl equivalent of the request it is doing. Label 'Code' on the right side at the same level of headers and body tabs.

Sorry for the late reply. The post in curl is the below:
`curl -X POST \
  'http://localhost:3000/jobs?account_id=eq.246432707' \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: localhost:3000' \
  -H 'Postman-Token: cc07c005-2ca9-4dc0-93b5-6061cd45bcdb,573aaded-b072-4dc3-abbd-81f489487366' \
  -H 'User-Agent: PostmanRuntime/7.13.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 1183' \
  -d ' {
        "account_id": 246211707,
        "title": "Manager of Quality Assurance Post",
        "description": "We are looking for a Manager of Quality Assurance to develop and execute exploratory tests as well as automated tests in order to ensure product quality. As a QA Engineer you will estimate, plan, and coordinate testing activities. You will also ensure that quality issues and defects are appropriately identified, documented, tracked, and resolved in our defect tracking system.",
        "state": "published",
        "created_at": "2019-04-20T00:00:00",
        "updated_at": "2019-06-20T13:22:13",
        "shortcode": "websoulchrome213",
        "published_on": "2019-04-20",
        "candidates_count":"0",
        "country_code": "GB",
        "state_code": "England",
        "city": "London",
        "telecommuting": "false",
        "approval_status": "approved",
        "postings_count": "0",
        "advertise_elsewhere": "false",
        "form_settings": {
            "phone": "enabled",
            "avatar": "enabled",
            "resume": "enabled",
            "address": "enabled",
            "summary": "enabled",
            "headline": "enabled",
            "education": "enabled",
            "experience": "enabled",
            "cover_letter": "enabled"
        },
        "visible": "true",
        "access_level": "0",
        "staffing": "true",
    }'`

I am using tha latest portgrest in docker which is last updated 5 months ago.

**Comment by stefanosvarsanis** [comment] 2019-06-24 14:31
Also I used the latest postgrest on mac and still get the same issue :(

**Comment by robx** [comment] 2019-06-24 14:47
Which postgresql version is this? Could you compare postgresql 9.6 vs postgresql 10?

**Comment by steve-chavez** [comment] 2020-01-24 18:05
@stefanosvarsanis Did you manage to solve this issue? Did you checked the postgresql version?

**Comment by steve-chavez** [comment] 2020-02-06 19:07
Closing until more feedback is given. It's likely it could be related to the pg version.

**Closed by steve-chavez** 2020-02-06 19:07 UTC
