### ISSUE TITLE
Resource embedding can not use  data."user"(id) as fk, but data."user2"(id) is fine

### ISSUE THREAD

**Issue by deftsp** [PostgREST/postgrest#1164] opened 2018-08-07 13:23 UTC
### Environment

* PostgreSQL version: 9.6
* PostgREST version: 0.5.00
* Operating system: Debian jessie

### Description of issue

With the following database
```
create schema data;

create table data."user" (id serial primary key, nickname  text not null);
create table data."user2" (id serial primary key, nickname  text not null);

create table data.book (title text, user_id integer references data."user"(id));
create table data.book2 (title text, user_id integer references data."user2"(id));

grant select, update on data."user", data."user2", data.book, data.book2 to api;

create schema api;
create view api.foo as (select * from data."user");
create view api.foo2 as (select * from data."user2");

create view api.bar as (select * from data.book);
create view api.bar2 as (select * from data.book2);

alter view api.foo owner to api;
alter view api.foo2 owner to api;
alter view api.bar owner to api;
alter view api.bar2 owner to api;

grant select, update on api.foo, api.foo2, api.bar, api.bar2 to web_anon;
```

```
curl "http://localhost:3002/foo?select=id,bar(title)"
{"message":"Could not find foreign keys between these entities, No relation found between foo and bar"}%
```
And the following one works 
```
curl "http://localhost:3002/foo2?select=id,bar2(title)"
[]
```

The only difference of the two examples is the table name( data."user" and data."user2").

**Comment by steve-chavez** [comment] 2018-08-07 18:08
This is already solved in master(duplicate of https://github.com/PostgREST/postgrest/issues/1129, also mentions the data."user" table).

You can [build from source](https://postgrest.org/en/v5.0/install.html#build-from-source)(should be straightforward on Debian) if you need the fix now.

**Closed by steve-chavez** 2018-08-07 18:08 UTC
