### ISSUE TITLE
Got endOfInput even if config file is mapped and readable

### ISSUE THREAD

**Issue by Jimexist** [PostgREST/postgrest#937] opened 2017-08-12 02:46 UTC
This is pertaining to docker v0.4.2.0

```sh
docker run --rm -v $(pwd)/postgrest.conf:/etc/postgrest/postgrest.conf -p 3000 -it begriffs/postgrest:v0.4.2.0 /bin/bash

root@11e9c4162571:/# cat /etc/postgrest/postgrest.conf
db-uri = "$(PGRST_DB_URI)"
db-schema = "$(PGRST_DB_SCHEMA)"
db-anon-role = "$(PGRST_DB_ANON_ROLE)"
db-pool = "$(PGRST_DB_POOL)"

server-host = "$(PGRST_SERVER_HOST)"
server-port = "$(PGRST_SERVER_PORT)"

server-proxy-uri = "$(PGRST_SERVER_PROXY_URI)"
jwt-secret = "$(PGRST_JWT_SECRET)"
secret-is-base64 = False

max-rows = "$(PGRST_MAX_ROWS)"
pre-request = "$(PGRST_PRE_REQUEST)"

root@11e9c4162571:/# ls -l /etc/postgrest/postgrest.conf
-rw-r--r-- 1 root root 380 Aug 12 02:40 /etc/postgrest/postgrest.conf

root@11e9c4162571:/# postgrest /etc/postgrest/postgrest.conf
postgrest: ParseError "/etc/postgrest/postgrest.conf" "endOfInput"
```

**Comment by Jimexist** [comment] 2017-08-13 11:27
some update: i think it was due to invalid config file. After i populated all the envvars the problem goes away.

I think it'll be helpful to output more explanatory error messages in this case.

**Comment by jlsphar** [comment] 2017-08-18 00:26
I'm seeing this message despite an hour or two trying to solve it. Populating all envvars doesn't change the outcome for me. Running docker v0.4.2.0. @Jimexist any chance you can share your configs (dockerfile+postgrest.conf)? I've checked against various issues/docs ~ 10 or so times now.

**Comment by Jimexist** [comment] 2017-08-18 02:38
@jlsphar i'm just filling out all the envvars with values in the config then i'm all good

**Comment by jlsphar** [comment] 2017-08-18 13:07
@Jimexist dang, i haven't been able to crack this shell. wish i had some haskell chops... my only experience with the language is using xmonad, a piece of software so great that i only need to play with the configuration. i'll take my issue over to gitter and see if we can't get this working :) thanks @Jimexist

**Comment by begriffs** [comment] 2017-09-29 05:16
@jlsphar in the project chat @jcasto reported the same problem.

Can you try running the `file` command on your config file, like

```bash
file myfile.conf
```

I'm curious if it will report a different encoding than I see locally for my own config file that works properly.

**Comment by jcasto** [comment] 2017-10-09 18:35
I am also fighting this problem.  

`
$ file postgrest.conf
postgrest.conf: ASCII text
`

**Comment by jcasto** [comment] 2017-10-09 22:21
It would appear that my password for my user was too complex, and the special characters in the file were causing the binary to not function as expected.

**Comment by geohuz** [comment] 2018-01-24 09:54
I have the same problem and solved by manually create a new file and typing all the lines in the file.

**Comment by rhysallister** [comment] 2019-04-19 13:25
Greetings, I had this issue as well, turned out that I was using single quotes to quote my strings.

**Comment by steve-chavez** [comment] 2019-07-26 18:29
@robx Have you seen a similar issue happen with [configurator-pg](https://github.com/robx/configurator-pg)?

**Comment by robx** [comment] 2020-03-07 14:12
@steve-chavez I haven't seen similar issues, but I'm also not really sure what the issue is here. I.e., there might well be some concrete issue where some wrongly quoted fields cause an unhelpful error message. I'd be happy to address such. As it stands, the issue is very vague to me.

**Comment by steve-chavez** [comment] 2020-03-07 17:36
@robx For now, I can reproduce the single quote issue:
```bash
## postgrest.conf
## ..
app.settings.external_api_secret = 'some_value'

## Will cause
postgrest postgrest.conf 
Error parsing config file:
        parsing support/configs/config: endOfInput
```

Though the main issue here is related to env var interpolation. In https://github.com/PostgREST/postgrest-heroku/issues/25#issuecomment-547604233 it's mentioned that a config like:

```bash
export TEST=".\"https://somedomain.example/key\""

## postgrest.conf
app.settings.external_api_secret = "$(TEST)"
```
Would cause the `endOfInput` error reported here, however I cannot reproduce it.

**Comment by robx** [comment] 2020-03-07 22:52
So it looks like due to the use of attoparsec any parse error will backtrack back to `endOfInput`. I'll have a look at switching it out for megaparsec.

**Comment by steve-chavez** [comment] 2020-03-12 15:08
The config error messages should be more descriptive now that #1457 got merged.

I'll close for now but will reopen if unclear errors are reported again.

**Closed by steve-chavez** 2020-03-12 15:08 UTC
Labels: config
