### ISSUE TITLE
Relation between table with view from same table

### ISSUE THREAD

**Issue by gregorgodoy** [PostgREST/postgrest#1307] opened 2019-05-27 18:14 UTC
### Environment

* PostgreSQL version: 10.7
* PostgREST version: 5.1.0
* Operating system: Ubuntu 16.04

### Description of issue

Cant embed view resource in table resource if view is from the same table. To simplify the issue I will use a silly example. I have a table called customer and a view called vcustomer and I want to embed vcustomer in costumer but get the error: `Could not find foreign keys between these entities, No relation found between customer and vcustomer`

Table definition
```
create table customer (
  customer_code varchar(16),
  customer_name varchar(255),
  customer_phone varchar(32),
  constraint pk_customer primary key (customer_code)
);

create or replace view vcustomer as 
  select customer_code, customer_name, customer_phone from customer;
```
Then I call postgrest API with this URL:
`api/customer?select=customer_code,customer_name,vcustomer(customer_phone)`

I expect:
```
[{
  "customer_code": "US190",
  "customer_name":"John Doe",
  "vcustomer": {
    "customer_phone":"+1547896587"
   }
}]
```
I get
```
{
    "message": "Could not find foreign keys between these entities, No relation found between customer and vcustomer"
}
```
Shouldn't table and view be related by the primary key? I think this is probably a bug.

**Comment by fenggy** [comment] 2019-06-03 07:25
i

**Comment by fenggy** [comment] 2019-06-03 07:26
I met the same problem, how to solve it? Bug or not support？

**Comment by gwn** [comment] 2019-07-07 06:53
To quote a relevant section from the docs:
> The server uses foreign keys to determine which tables and views can be returned together.

http://postgrest.org/en/v5.2/api.html#resource-embedding

There are no columns that have foreign key indexes in your example so it won't work. PostgREST has no way of understanding that you want to relate the two resources.

For the purposes of the (untested) example below I'm assuming that customers can have related customers so we can define a foreign key relationship between them, hence demonstrate resource embedding.

```
create table customer (
  customer_code varchar(16),
  customer_name varchar(255),
  customer_phone varchar(32),
  related_customer_code varchar(16),
  constraint pk_customer primary key (customer_code),
  foreign key (related_customer_code) references customer (customer_code)
);
```

```
api/customer?select=customer_code,customer_name,related_customer:customer(customer_phone)
```

This is definitely not a bug; so I encourage you to close the issue and ask for support in a Q&A platform like StackOverflow if my answer did not help you. And please be sure to read the relevant parts of the manual more carefully.

**Comment by steve-chavez** [comment] 2019-07-18 23:46
Totally correct by @gwn.

I'll also add that we have several tests for self-referencing **foreign keys**:

https://github.com/PostgREST/postgrest/blob/afb7266f17510a38c06cff402e2270d6e53ee917/test/fixtures/schema.sql#L1376-L1381 

https://github.com/PostgREST/postgrest/blob/afb7266f17510a38c06cff402e2270d6e53ee917/test/Feature/QuerySpec.hs#L580-L605

So as long as you have a foreign key in your table, the view should be embeddable with it.

**Comment by steve-chavez** [comment] 2019-07-18 23:51
Closing, will highlight the foreign keys restriction on the docs.

**Closed by steve-chavez** 2019-07-18 23:51 UTC
