### ISSUE TITLE
Cannot filter by JSON equality

### ISSUE THREAD

**Issue by begriffs** [PostgREST/postgrest#336] opened 2015-10-31 02:50 UTC
e.g. `GET http://localhost:3000/json?data=eq.{"foo":"bar"}`. It returns

``` json
{
  "hint": "No operator matches the given name and argument type(s). You might need to add explicit type casts.",
  "details": null,
  "code": "42883",
  "message": "operator does not exist: json = unknown"
}
```

Bug is present in 0.2.12 and 0.3 candidate. Url encoding the json does not help.

**Comment by ruslantalpa** [comment] 2015-11-02 12:59
This is a combination of a few issue, basically what is happening here is this
```
select * from "1".complex_items where settings = '{"a":1}'
```
and it fails
but if you do
```
select * from "1".complex_items where settings::jsonb = '{"a":1}'
```
it works.

I would say it works as expected with a few mentions:
The users can check fore equality for any part inside the json with ->> and it works but not the whole json column.
Whenever we return a location header where there are no keys but there is a json column, the url will not work.
I would clasiffy this as low priority since there are workarounds (use jsonb instead of json, have keys on table, filter based on data within json column)

**Comment by begriffs** [comment] 2015-11-03 01:31
Sort of low priority, I agree. Although I noticed it when testing the urls appearing in the Location header for newly posted json data. They are of this form and are broken.

Interestingly when I altered one of the tables to use an actual jsonb column rather than doing a typecast in the query it still fails.

**Comment by ruslantalpa** [comment] 2016-06-01 13:21
the location header issue was addressed and since the root of the problem here comes from the fact that the data type does not support equality, i would say this is not a bug, it's the same as saying `select 'a'+'b'` not being supported is a bug. ... close :)

**Comment by begriffs** [comment] 2016-06-01 20:15
For good measure we should update [this test](https://github.com/begriffs/postgrest/blob/master/test/Feature/InsertSpec.hs#L168-L178) to not only insert a jsonb object but attempt to GET the url provided in the resulting location header and check it succeeds.

**Comment by steve-chavez** [comment] 2018-01-26 15:56
I think this issue can be closed by:

- Adding a test to ensure that a `jsonb` column can be filtered by equality.
- Enable the `Location` header only for tables with a PK. If the table has no PK the `Location` will be misleading, also don't think `json/jsonb` columns are good candidates for PK so I'll add a test with a different data type for this.

@begriffs Let me know what you think.

**Comment by steve-chavez** [comment] 2018-06-19 18:01
Closing this since #1128 got merged, it included a test for jsonb equality in https://github.com/PostgREST/postgrest/pull/1128/commits/610ac4b74340badfb95905c3294104936ebdd11d.

**Closed by steve-chavez** 2018-06-19 18:01 UTC
Labels: bug, minor
