### ISSUE TITLE
Admin server returns HTTP 503 in 12.x

### ISSUE THREAD

**Issue by mkleczek** [PostgREST/postgrest#3128] opened 2023-12-19 15:46 UTC
### Environment

* PostgreSQL version: 14
* PostgREST version: 12.0.0 and 12.0.1
* Operating system: **Windows**

### Description of issue

Command to start postgrest:

PGRST_ADMIN_SERVER_PORT=3001 PGUSER=postgres PGPASSWORD=[password] postgrest.exe

Version 11.2.2 starts and returns HTTP OK from http://localhost:3001/ready and http://localhost:3001/live

Version 12.0.x starts but returns HTTP 503 from both above URLs

**Comment by steve-chavez** [comment] 2023-12-19 18:28
This is likely related to https://github.com/PostgREST/postgrest/pull/3034

cc @develop7

**Comment by develop7** [comment] 2023-12-19 19:04
Yup, will look into tomorrow

**Comment by develop7** [comment] 2023-12-25 17:27
> ```
> PGRST_ADMIN_SERVER_PORT=3001 PGUSER=postgres PGPASSWORD=[password] postgrest.exe
> ```

@mkleczek I don't think CMD or PowerShell support such syntax, what shell are you using? If mingw/cygwin and/or WSL are involved, I'd like to know that too. In fact, now that postgrest installed from scoop doesn't run for me (which is another issue to file), I'd like to know even more details about your Windows & postgrest setup to reproduce the issue.

Thank you in advance.

**Comment by mkleczek** [comment] 2023-12-25 20:12
Ahh, right. I run it from Git bash shell. I guess it is mingw then?

**Comment by mkleczek** [comment] 2023-12-26 19:42
2.43.0 (I suppose you mean Git release: https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.exe

If you mean Postgrest release then it's provided here: both 12.0.0 and 12.0.1

**Comment by develop7** [comment] 2024-01-09 15:51
Thank you for your patience. Could you do post the output of `postgrest.exe --dump-config` here as well (masking sensitive data, of course)?

**Comment by mkleczek** [comment] 2024-01-14 19:40
Will try to provide it but there is no configuration except the environment variables provided in the description.

**Comment by develop7** [comment] 2024-01-14 19:51
> there is no configuration except the environment variables provided in the description.

Yes, and default configuration too, which I am after.

**Comment by develop7** [comment] 2024-02-19 17:19
> Could you do post the output of `postgrest.exe --dump-config` here as well

I've managed to get it, here:

<details>
<summary>postgrest.exe --dump-config</summary>

```config
db-aggregates-enabled = false
db-anon-role = ""
db-channel = "pgrst"
db-channel-enabled = true
db-extra-search-path = "public"
db-max-rows = ""
db-plan-enabled = false
db-pool = 10
db-pool-acquisition-timeout = 10
db-pool-max-lifetime = 1800
db-pool-max-idletime = 30
db-pool-automatic-recovery = true
db-pre-request = ""
db-prepared-statements = true
db-root-spec = ""
db-schemas = "public"
db-config = true
db-pre-config = ""
db-tx-end = "commit"
db-uri = "postgresql://"
jwt-aud = ""
jwt-role-claim-key = ".\"role\""
jwt-secret = ""
jwt-secret-is-base64 = false
jwt-cache-max-lifetime = 0
log-level = "error"
openapi-mode = "follow-privileges"
openapi-security-active = false
openapi-server-proxy-uri = ""
server-cors-allowed-origins = ""
server-host = "!4"
server-port = 3000
server-trace-header = ""
server-timing-enabled = false
server-unix-socket = ""
server-unix-socket-mode = "660"
admin-server-port = ""
```

</details>

**Comment by develop7** [comment] 2024-02-19 17:38
@mkleczek consider setting [`server-host`](https://postgrest.org/en/v12/references/configuration.html#server-host) to explicit IP/hostname instead of the default `!4`, this seems to work the issue around:

```
PS > $env:PGRST_SERVER_HOST = '127.0.0.1'; postgrest.exe
```
and 
```
PS C:\Program Files\PostgreSQL\16> curl -v "http://localhost:3001/ready"
*   Trying [::1]:3001...
*   Trying 127.0.0.1:3001...
* Connected to localhost (127.0.0.1) port 3001
> GET /ready HTTP/1.1
> Host: localhost:3001
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Mon, 19 Feb 2024 17:35:06 GMT
< Server: postgrest/12.0.2 (a4e00ff)
<
* Connection #0 to host localhost left intact
PS C:\Program Files\PostgreSQL\16> curl -v "http://localhost:3001/live"
*   Trying [::1]:3001...
*   Trying 127.0.0.1:3001...
* Connected to localhost (127.0.0.1) port 3001
> GET /live HTTP/1.1
> Host: localhost:3001
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Mon, 19 Feb 2024 17:35:12 GMT
< Server: postgrest/12.0.2 (a4e00ff)
<
* Connection #0 to host localhost left intact
```

**Comment by develop7** [comment] 2024-02-20 11:28
Duplicate of #3204 it is

**Closed by develop7** 2024-02-20 11:28 UTC
Labels: bug

**Comment by mkleczek** [comment] 2024-02-29 04:27
Sorry for long silence (been away) and thanks for info - will verify ASAP
