### ISSUE TITLE
Add an option to limit initialisation script to listed schemas

### ISSUE THREAD

**Issue by nextstopsun** [PostgREST/postgrest#2023] opened 2021-11-15 11:30 UTC
PostgREST init query can be real tough for a database with FDW objects inside. 
I've had this issue numerous times: fdws could be different and point to different kinds of sources (in my case oracle, ogr datasources, http services). So the retrieval of metadata for such objects may involve reading the whole source.
That prevents postgrest from starting fast and in some cases puts the db into a recovery state.

A possible solution might be adding options to limit database schemas for introspection during startup.

**Comment by wolfgangwalther** [comment] 2021-11-15 11:32
Seems to be a duplicate of #2015. If that's not the case, please provide more detail.

**Closed by wolfgangwalther** 2021-11-15 11:32 UTC
Labels: duplicate
