### ISSUE TITLE
generated OpenAPI spec doesn't reflect users privileges 

### ISSUE THREAD

**Issue by adrian-gierakowski** [PostgREST/postgrest#2443] opened 2022-08-22 10:27 UTC
### Environment

* PostgreSQL version: (if using docker, specify the image)

14.3

* PostgREST version: (if using docker, specify the image)

9.0.1.20220717

* Operating system:

linux (nixos, debian)

### Description of issue

Given following schema:

```sql
CREATE SCHEMA api;

CREATE TABLE api.write_only (
  id bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  data text NOT NULL
);

CREATE TABLE api.read_only (
  id bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  data text NOT NULL
);

CREATE ROLE web_anon NOLOGIN;
GRANT USAGE ON SCHEMA api TO web_anon;
GRANT INSERT (data) ON TABLE api.write_only TO web_anon;
GRANT SELECT ON TABLE api.read_only TO web_anon;

```

And `postgrest` started with `PGRST_OPENAPI_MODE=follow-privileges`, the OpenAPI spec returned at http://localhost:8080/ doesn't reflect the specific privileges given to wed_anon:
1. both `/write_only` and `/read_only` routes include 4 method (`GET`, `POST`, `DELETE`, `PATCH`) even though the privileges only allow `web_anon` to `POST` to `/write_only` and `GET` `/read_only`. 
2. `write_only.id` is not writable by wed_anon but the generated spec suggests that it is

**Comment by adrian-gierakowski** [comment] 2022-08-22 10:34
![Screenshot_20220822_112852](https://user-images.githubusercontent.com/330177/185901272-0f991b86-156a-46aa-9518-8a8676d50735.png)
![Screenshot_20220822_113357](https://user-images.githubusercontent.com/330177/185901286-b6dc5598-ac35-449c-a1ca-c94d639dcab6.png)

**Comment by laurenceisla** [comment] 2022-08-23 01:19
Yes, this is a known issue, it looks like a duplicate of #1870. This was the answer there:

> The only reason is that a more fine-grained output is not implemented, yet. We are unlikely to make major changes to the OpenAPI output right now, because we expect to move it out of core alltogether (see https://github.com/PostgREST/postgrest/issues/1698). Once we have solved that, we're in a much better position to improve OpenAPI a lot.

Although we are still doing small changes to OpenAPI here and there, this one does not look like a simple change. I'll close this in favor of the other issue.

**Closed by laurenceisla** 2022-08-23 01:19 UTC
Labels: OpenAPI
